apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mail-pass
  namespace: monitoring
  labels:
    release: monitoring
data:
  gmail-pass: <<ENTER_YOUR_APP PASSWORDS_IN_BASE64_ENCODED_FORMAT>>


#here password go to gmail security type app paasowrd copy it do   use this echo "xgkf zypm pvxp ahzw" | base64 -d


