apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: prometheus
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - expense

  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app

  endpoints:
  - port: backend   # MUST match service port name
    path: /metrics
    interval: 15s